name: frontend
description: A new Flutter project for the frontend app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  webview_flutter: ^4.7.0
  dart_geohash: ^2.1.0
  http: any
  intl: ^0.20.2
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.0

dev_dependencies:
  fake_cloud_firestore: ^2.4.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
